### ISSUE TITLE
PIXI.filters vs PIXI.Filter

### ISSUE THREAD

**Issue by PSeitz** [pixijs/pixi-extra-filters#15]
Hi,

PIXI.Filter is not defined in Pixi v3 or v4, but the lib tries to extend the PIXI.Filter

GlowFilter.prototype = Object.create(PIXI.Filter.prototype);

**Comment by englercj** [comment]
It is defined in v4:

https://github.com/pixijs/pixi.js/blob/dev/src/core/index.js#L60

https://github.com/pixijs/pixi-extra-filters/blob/master/package.json#L43

**Comment by PSeitz** [comment]
Ah I see it's defined in the dev branch, but not in the release candidate, quite confusing
