### ISSUE TITLE
glslify is not defined

### ISSUE THREAD

**Issue by hopewise** [pixijs/pixi-extra-filters#17]
Hello,

I've just tried to use GlowFilter, but I got this error:

```
pixi-extra-filters.min.js:1 Uncaught ReferenceError: glslify is not defined
```

I only included `pixi-extra-filters.min.js` , please advice which file to include also.
Thanks

**Comment by ivanpopelyshev** [comment]
There's that branch: https://github.com/pixijs/pixi-extra-filters/tree/fix-missing-glslify

But I'm gonna update master now :)

**Comment by ivanpopelyshev** [comment]
OH, I also see problems with GlowFilter and other stuff, it just wont compile

**Comment by ivanpopelyshev** [comment]
Soooo, its fixed! Please check it.

**Comment by hopewise** [comment]
I will, when I return home 😃

**Comment by hopewise** [comment]
Ok, I've tested it, here is my comments:

The glow filter constructor is documentation is different than in implementation:

> - @example
>   -  someSprite.filters = [
>   -      new GlowFilter(renderer.width, renderer.height, 15, 2, 1, 0xFF0000, 0.5)
>   -  ];
>     */
>     function GlowFilter(distance, outerStrength, innerStrength, color, quality)  

Also, I've noticed that the glow is cropped,as in my result:
![image](https://cloud.githubusercontent.com/assets/1061157/19226791/d8263eb6-8eb8-11e6-8a76-2d9e1b6c94f2.png)

It seems that the glow effect is only within the sprite width& height, that's why the effect is cropped?

**Comment by englercj** [comment]
Add some padding to the filter (`.padding`)

**Comment by hopewise** [comment]
Can you please show me an example about setting padding?

**Comment by englercj** [comment]
``` js
var filter = new Filter();
filter.padding = 10;
```

**Comment by hopewise** [comment]
thanks, is it possible to tween a filter parameter? like distance or color? from value x to value y in a certain length of time?

**Comment by ivanpopelyshev** [comment]
Distance is not possible, because its backed into shader.

**Comment by hopewise** [comment]
Can you please have a look at this http://dcaclab.com/en/experiments/9900-a-simple-test-circuit
You need flash player to see it, what do you advice to achieve such a result?

**Comment by ivanpopelyshev** [comment]
You can animate innerStrenth and outerStrength, i suppose?

**Comment by hopewise** [comment]
I will test and send you my feedback, thank you.

**Comment by ivanpopelyshev** [comment]
Actually, your glow is too big, its certainly not for realtime. Use photoshop to generate texture for the glow and use it as a transparent sprite with MULTIPLY or ADD blendmode or instead.

GlowFilter and OutlineFilter were made for 1px-10px, not that monstrosity!

**Comment by hopewise** [comment]
Thanks for advice, I will do some testing.. maybe, 10px is not bad too, but I might have several lightbulbs animating .. any performance tips would be appreciated too, but I have to test and compare..

**Comment by hopewise** [comment]
I've tried to tween outerStrength, however, when I do `renderer.render(_container);` on each tween update, I got poor performance while updating.. isn't there another way to update stage?

**Comment by ivanpopelyshev** [comment]
dont call render() inside tween, make it in RAF. If you want to cal render() less times, just make a timer with 20FPS or so.

 You can also define "sleep" flag

``` js
//somewhere in RAF
if (awake>0) { awake--;render(); }
```

now every time you change something, make 

``` js
awake=5
```

that way it will stop rendering when there's no action

**Comment by hopewise** [comment]
thanks, by the way, I've just checked your game gameofbombs.com 👍  do you use pub, sub programming model to synch players locations? what tech did you use for that❓
