### ISSUE TITLE
SimpleLightmapFilter

### ISSUE THREAD

**Issue by Oza94** [pixijs/pixi-extra-filters#9]
Hello,

I've just created a simple lightmap filter for my needs. [Here is a codepen](http://codepen.io/Oza94/pen/EPoRxj) and [here is the tutorial I used](http://www.alcove-games.com/opengl-es-2-tutorials/lightmap-shader-fire-effect-glsl/).

This is sufficient for simple needs, it takes in arguments : 
- The lightmap texture
- The ambient color
- The screen resolution

Here is a demo of the filter in action from the codepen above : 

![Filter demo](http://i.imgur.com/sC2qAQn.png)

I think this can be a good addition to pixi-extras-filters. I can provide everything from the code to the doc. But may be this is not relevant? Let me know.

**Comment by englercj** [comment]
Just make a PR :)

**Comment by GoodBoyDigital** [comment]
Agreed this is really cool! nice job :+1:
